spring:
  cloud:
    config:
      name: myapp

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

messaging:
  controller: "Atualiza a entrega no controller"

