spring:
  cloud:
    config:
      name: myapp

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

messaging:
  controller: "Mudanca feita e atualiza a entrega no controller 2"

